# Generated by Django 6.1.1 on 2026-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتریان",
            },
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="شهر"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره تماس"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
        ),
    ]
