# Generated by Django 6.1.1 on 2026-10-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_customer_options_alter_customer_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "تماس تلفنی"),
                            ("email", "ایمیل"),
                            ("meeting", "جلسه"),
                            ("task", "وظیفه"),
                            ("note", "یادداشت"),
                        ],
                        max_length=20,
                        verbose_name="نوع فعالیت",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ سررسید"
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="انجام شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "فعالیت",
                "verbose_name_plural": "فعالیت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="مبلغ (ریال)",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "بررسی اولیه"),
                            ("proposal", "ارائه پیشنهاد"),
                            ("negotiation", "مذاکره"),
                            ("won", "برنده شده"),
                            ("lost", "از دست رفته"),
                        ],
                        default="prospecting",
                        max_length=20,
                        verbose_name="مرحله",
                    ),
                ),
                (
                    "probability",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="مقدار بین ۰ تا ۱۰۰",
                        verbose_name="احتمال موفقیت (%)",
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="تاریخ پیش\u200cبینی بسته شدن",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "معامله",
                "verbose_name_plural": "معاملات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="شرکت"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "وب\u200cسایت"),
                            ("referral", "معرفی"),
                            ("social", "شبکه\u200cهای اجتماعی"),
                            ("email", "ایمیل"),
                            ("call", "تماس تلفنی"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="منبع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("contacted", "تماس گرفته شده"),
                            ("qualified", "واجد شرایط"),
                            ("converted", "تبدیل شده"),
                            ("lost", "از دست رفته"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "سرنخ",
                "verbose_name_plural": "سرنخ\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "یادداشت",
                "verbose_name_plural": "یادداشت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "کم"),
                            ("medium", "متوسط"),
                            ("high", "بالا"),
                            ("urgent", "فوری"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("in_progress", "در حال بررسی"),
                            ("resolved", "حل شده"),
                            ("closed", "بسته شده"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ حل"
                    ),
                ),
            ],
            options={
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="company",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="شرکت"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(
                blank=True,
                default="ایران",
                max_length=100,
                null=True,
                verbose_name="کشور",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="یادداشت"),
        ),
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[("active", "فعال"), ("inactive", "غیرفعال"), ("vip", "ویژه")],
                default="active",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customers_c_email_4fdeb3_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["status"], name="customers_c_status_ce44cf_idx"),
        ),
        migrations.AddField(
            model_name="activity",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="customers.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="customers.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_lead",
                to="customers.customer",
                verbose_name="مشتری تبدیل\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="customers.lead",
                verbose_name="سرنخ",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_notes",
                to="customers.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_notes",
                to="customers.deal",
                verbose_name="معامله",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_notes",
                to="customers.lead",
                verbose_name="سرنخ",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="customers.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["stage"], name="customers_d_stage_d884d2_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="customers_l_status_652ef1_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["source"], name="customers_l_source_7f5339_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="customers_t_status_fd09f3_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["priority"], name="customers_t_priorit_d93f95_idx"
            ),
        ),
    ]
